version: "3.4"
services:
  server:
    image: "ghcr.io/ledouxm/minitainer-sample2:${TAG:-main}"
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - HTTP_HOST=${HTTP_HOST}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    ports:
      - "${HTTP_PORT}"
    networks:
      - nginx-network
    profiles:
      - production
networks:
  nginx-network:
    external: true
    name: nginx-network
